import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const AlertModal = dynamic(() => import("@/app/components/modal/AlertModal"), {
  ssr: false,
});
const ConfirmModal = dynamic(
  () => import("@/app/components/modal/ConfirmModal"),
  { ssr: false }
);

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Review-it",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} font-base`}>
      <body>
        <Header />
        <div className="layout">{children}</div>
        <AlertModal />
        <ConfirmModal />
        <SpeedInsights />
      </body>
    </html>
  );
}
